// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TCIP.Infrastructure.Data;

#nullable disable

namespace TCIP.Infrastructure.Migrations
{
    [DbContext(typeof(TcipDbContext))]
    [Migration("20260903025921_SimplifyReminderRepetition")]
    partial class SimplifyReminderRepetition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TCIP.Business.Modules.AccessControl.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.AccessControl.Domain.Entities.PermissionGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GrantedByPrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_principal_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid?>("ResourcePrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_principal_id");

                    b.Property<Guid>("SubjectPrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_principal_id");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("ResourcePrincipalId");

                    b.HasIndex("SubjectPrincipalId", "PermissionId", "ResourcePrincipalId")
                        .IsUnique();

                    b.ToTable("permission_grants", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.AccessControl.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.AccessControl.Domain.Entities.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GrantedByPrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_principal_id");

                    b.Property<Guid?>("ResourcePrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_principal_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("SubjectPrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_principal_id");

                    b.HasKey("Id");

                    b.HasIndex("ResourcePrincipalId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SubjectPrincipalId", "RoleId", "ResourcePrincipalId")
                        .IsUnique();

                    b.ToTable("role_assignments", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.AccessControl.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("EndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at_utc");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("text")
                        .HasColumnName("recurrence_rule");

                    b.Property<DateTimeOffset>("StartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Status", "StartAtUtc");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("ck_events_end_after_start", "end_at_utc IS NULL OR end_at_utc >= start_at_utc");
                        });
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.EventAudience", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("EventId", "PrincipalId");

                    b.HasIndex("PrincipalId", "Status", "EventId");

                    b.ToTable("event_audiences", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.EventOccurrenceException", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("OriginalStartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_start_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("EndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at_utc");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cancelled");

                    b.Property<DateTimeOffset?>("StartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("EventId", "OriginalStartAtUtc");

                    b.ToTable("event_occurrence_exceptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_occurrence_exceptions_cancelled", "(is_cancelled = TRUE AND start_at_utc IS NULL AND end_at_utc IS NULL) OR (is_cancelled = FALSE AND (start_at_utc IS NOT NULL OR end_at_utc IS NOT NULL))");

                            t.HasCheckConstraint("ck_event_occurrence_exceptions_end_after_start", "is_cancelled = TRUE OR end_at_utc IS NULL OR start_at_utc IS NULL OR end_at_utc > start_at_utc");
                        });
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.EventTranslation", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("EventId", "Language");

                    b.ToTable("event_translations", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EffectiveStartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_start_at_utc");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("OriginalStartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_start_at_utc");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<Guid>("ReminderRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("reminder_rule_id");

                    b.Property<DateTimeOffset>("ScheduledFireAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_fire_at_utc");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("RecipientUserId", "ReadAtUtc", "SentAtUtc");

                    b.HasIndex("ReminderRuleId", "OriginalStartAtUtc", "ScheduledFireAtUtc", "RecipientUserId")
                        .IsUnique();

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("EventVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurrenceStartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurrence_start_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<DateTimeOffset?>("PublishingLeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publishing_lease_expires_at_utc");

                    b.Property<Guid>("ReminderRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("reminder_rule_id");

                    b.Property<DateTimeOffset>("ScheduledFireAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_fire_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.HasIndex("ReminderRuleId", "OccurrenceStartAtUtc", "ScheduledFireAtUtc", "EventVersion")
                        .IsUnique();

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_attempt_count", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.ReminderRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("MaxLatenessMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("max_lateness_minutes");

                    b.Property<string>("MisfirePolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("misfire_policy");

                    b.Property<int>("RemindBeforeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("remind_before_minutes");

                    b.Property<int?>("RepeatEveryMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("repeat_every_minutes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Status");

                    b.ToTable("reminder_rules", null, t =>
                        {
                            t.HasCheckConstraint("ck_reminder_rules_max_lateness", "max_lateness_minutes >= 0");

                            t.HasCheckConstraint("ck_reminder_rules_remind_before", "remind_before_minutes >= 0");

                            t.HasCheckConstraint("ck_reminder_rules_repeat_interval", "repeat_every_minutes IS NULL OR repeat_every_minutes > 0");
                        });
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.ReminderSchedule", b =>
                {
                    b.Property<Guid>("ReminderRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("reminder_rule_id");

                    b.Property<long>("EventVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("event_version");

                    b.Property<DateTimeOffset>("NextFireAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_fire_at_utc");

                    b.Property<DateTimeOffset>("OccurrenceStartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurrence_start_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ReminderRuleId");

                    b.HasIndex("Status", "NextFireAtUtc");

                    b.ToTable("reminder_schedules", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PrincipalId")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId")
                        .IsUnique();

                    b.HasIndex("Name", "Type")
                        .IsUnique();

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.Principal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("available");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("Available", "Id");

                    b.ToTable("principals", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.PrincipalMembership", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<DateTimeOffset?>("LeftAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at_utc");

                    b.HasKey("UserId", "PrincipalId");

                    b.HasIndex("PrincipalId", "LeftAtUtc");

                    b.ToTable("principal_memberships", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PrincipalId")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.ProjectTranslation", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("ProjectId", "Language");

                    b.ToTable("project_translations", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PrincipalId")
                        .IsUnique();

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.UserPosition", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.HasKey("UserId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("user_positions", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Identity.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset?>("LastRotatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_rotated_at_utc");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("en")
                        .HasColumnName("language");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("User")
                        .HasColumnName("role");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("UTC")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TCIP.Business.Modules.AccessControl.Domain.Entities.PermissionGrant", b =>
                {
                    b.HasOne("TCIP.Business.Modules.AccessControl.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCIP.Business.Modules.Directory.Domain.Entities.Principal", "ResourcePrincipal")
                        .WithMany()
                        .HasForeignKey("ResourcePrincipalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TCIP.Business.Modules.Directory.Domain.Entities.Principal", "SubjectPrincipal")
                        .WithMany()
                        .HasForeignKey("SubjectPrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("ResourcePrincipal");

                    b.Navigation("SubjectPrincipal");
                });

            modelBuilder.Entity("TCIP.Business.Modules.AccessControl.Domain.Entities.RoleAssignment", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Directory.Domain.Entities.Principal", "ResourcePrincipal")
                        .WithMany()
                        .HasForeignKey("ResourcePrincipalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TCIP.Business.Modules.AccessControl.Domain.Entities.Role", "Role")
                        .WithMany("SubjectAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCIP.Business.Modules.Directory.Domain.Entities.Principal", "SubjectPrincipal")
                        .WithMany("SubjectAssignments")
                        .HasForeignKey("SubjectPrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourcePrincipal");

                    b.Navigation("Role");

                    b.Navigation("SubjectPrincipal");
                });

            modelBuilder.Entity("TCIP.Business.Modules.AccessControl.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("TCIP.Business.Modules.AccessControl.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCIP.Business.Modules.AccessControl.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.Event", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Identity.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.EventAudience", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Calendar.Domain.Entities.Event", "Event")
                        .WithMany("Audiences")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCIP.Business.Modules.Directory.Domain.Entities.Principal", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.EventOccurrenceException", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Calendar.Domain.Entities.Event", "Event")
                        .WithMany("OccurrenceExceptions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.EventTranslation", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Calendar.Domain.Entities.Event", "Event")
                        .WithMany("Translations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.Notification", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Calendar.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCIP.Business.Modules.Identity.Domain.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCIP.Business.Modules.Calendar.Domain.Entities.ReminderRule", "ReminderRule")
                        .WithMany()
                        .HasForeignKey("ReminderRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("RecipientUser");

                    b.Navigation("ReminderRule");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.ReminderRule", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Calendar.Domain.Entities.Event", "Event")
                        .WithMany("ReminderRules")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.ReminderSchedule", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Calendar.Domain.Entities.ReminderRule", "ReminderRule")
                        .WithOne("Schedule")
                        .HasForeignKey("TCIP.Business.Modules.Calendar.Domain.Entities.ReminderSchedule", "ReminderRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReminderRule");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.Department", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Directory.Domain.Entities.Principal", "Principal")
                        .WithOne("Department")
                        .HasForeignKey("TCIP.Business.Modules.Directory.Domain.Entities.Department", "PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.Group", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Directory.Domain.Entities.Principal", "Principal")
                        .WithOne("Group")
                        .HasForeignKey("TCIP.Business.Modules.Directory.Domain.Entities.Group", "PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.PrincipalMembership", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Directory.Domain.Entities.Principal", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCIP.Business.Modules.Identity.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Principal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.Project", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Identity.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TCIP.Business.Modules.Directory.Domain.Entities.Principal", "Principal")
                        .WithOne("Project")
                        .HasForeignKey("TCIP.Business.Modules.Directory.Domain.Entities.Project", "PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.ProjectTranslation", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Directory.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.Team", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Directory.Domain.Entities.Principal", "Principal")
                        .WithOne("Team")
                        .HasForeignKey("TCIP.Business.Modules.Directory.Domain.Entities.Team", "PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.UserPosition", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Directory.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCIP.Business.Modules.Identity.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Identity.Domain.Entities.Session", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Identity.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.HasOne("TCIP.Business.Modules.Directory.Domain.Entities.Principal", "Principal")
                        .WithOne("User")
                        .HasForeignKey("TCIP.Business.Modules.Identity.Domain.Entities.User", "PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("TCIP.Business.Modules.AccessControl.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TCIP.Business.Modules.AccessControl.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("SubjectAssignments");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.Event", b =>
                {
                    b.Navigation("Audiences");

                    b.Navigation("OccurrenceExceptions");

                    b.Navigation("ReminderRules");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Calendar.Domain.Entities.ReminderRule", b =>
                {
                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("TCIP.Business.Modules.Directory.Domain.Entities.Principal", b =>
                {
                    b.Navigation("Department");

                    b.Navigation("Group");

                    b.Navigation("Project");

                    b.Navigation("SubjectAssignments");

                    b.Navigation("Team");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
